### ISSUE TITLE
Argument from caller macro is incorrectly passed through to callee macro?

### ISSUE THREAD

**Issue by jgerigmeyer** [mozilla/nunjucks#478]
If a macro is called (using ``{% call %}``) with an argument, and the ``caller()`` is itself a macro that accepts an argument with the same name with a default of ``none``, the argument from the ``caller`` macro is incorrectly passed through to the ``callee`` macro. That sounds ridiculously confusing, so here's the test case:

```
{% macro inner(class=none) %}
  <div class="{{ class }}"></div>
{% endmacro %}

{% macro outer(class=none) %}
  <div class="{{ class }}">
    {{ caller() }}
  </div>
{% endmacro %}

{% call outer(class='outer') %}
  {{ inner() }}
{% endcall %}
```

When rendered via jinja2, this is the output:

```
<div class="outer">
  <div class="None"></div>
</div>
```

However, when rendered via nunjucks, the output is:

```
<div class="outer">
  <div class="outer"></div>
</div>
```

This seems to only happen when the default for the ``inner`` arg is ``none``; it doesn't occur when the default is ``''`` or ``false``.

**Comment by carljm** [comment]
Interesting! I'll look into this. I wonder if it's just arguments, or works for any variable of a matching name in the calling namespace...

**Comment by carljm** [comment]
This was partly fixed by #667 -- macro frames are now totally separated from the calling frame, so there's no longer any way for a macro to reach out and see or touch its calling frame. So you can no longer see this behavior with macro arguments with a default of `none`. Looking into whether it can still crop up in other situations...

**Comment by jgerigmeyer** [comment]
I'm still seeing this bug (or seeing it again?):

http://jsfiddle.net/jgerigmeyer/tro6jhy9/1/
http://jsfiddle.net/jgerigmeyer/6cL8wqd7/1/
