### ISSUE TITLE
Too Much Recursion, Windows Firefox

### ISSUE THREAD

**Issue by spattersongt** [mozilla/nunjucks#880]
I'm running into a problem on Window 7 and 10 on basically ALL recent Firefox versions.  Even on the most *basic* of templates (only a few includes, no macros, a few nested if statements) I get "Template error: too much recursion"   Has anyone else seen this?

I'll try and get a basic, isolated failing test next week (assuming I can get permission from my employer to post some of our template code).

**Comment by vecmezoni** [comment]
Try to check nunjucks from master, issue like this was fixed in https://github.com/mozilla/nunjucks/pull/787

**Comment by spattersongt** [comment]
I've tried the 3.0.0-dev3 branch and I've verified it's using the new waterfall call structure.  Unfortunately that didn't solve our issues.  

I'll try to get an isolated test soon.  Our setup is a bit complicated (babel, webpack, nunjucks-loader) but I think we can strip down something to the barebones.

**Comment by spattersongt** [comment]
Well I don't have a standalone test... but turning off jinja2 compat fixed it for me.  

I was able to narrow it down to here:

```
  runtime.memberLookup = function(obj, val, autoescape) { // jshint ignore:line
    //obj = obj || {};

    // If the object is an object, return any of the methods that Python would
    // otherwise provide.
    if (lib.isArray(obj) && ARRAY_MEMBERS.hasOwnProperty(val)) {
      return function() {return ARRAY_MEMBERS[val].apply(obj, arguments);};
    }

    if (lib.isObject(obj) && OBJECT_MEMBERS.hasOwnProperty(val)) {
      return function() {return OBJECT_MEMBERS[val].apply(obj, arguments);};
    }

    return orig_memberLookup.apply(this, arguments);
  };
```

if i uncommented the ```obj = obj || {}``` line it breaks again in Windows 7 Firefox 49

**Comment by spattersongt** [comment]
https://github.com/spattersongt/nunjucks-recursion-error

Heres a reproducible case.  It seems to be tied to the number of includes.  See the readme on how to run.
